### ISSUE TITLE
The size of the image input to Swin Transformer

### ISSUE THREAD

**Issue by shilinyan99** [yoxu515/aot-benchmark#1]
I notice that Swin Transformer uses pre-training parameters, and I would like to ask you whether the image size input into Swin Transformer is also 224*224?

**Comment by z-x-yang** [comment]
No. The input size has two restrictions in default: (1) No more than 1.3*480p resolution; (2) The edge size should be 16N+1 (if MODEL_ALIGN_CORNERS=Ture) or 16N (if MODEL_ALIGN_CORNERS=False).

**Comment by shilinyan99** [comment]
Sorry, I do not understand this. When encoder is SwinB, the initial weights were trained with Imagnet22k and input image size is 224*224. If your input size is not 224 * 224, the number of corresponding patches will change. Can you input the next linear layer? Maybe I have a wrong understanding of swinB~~
Thank you!

**Comment by z-x-yang** [comment]
Swin Transformers perform like CNNs since sliding windows are used. In fact, you can use any input size you want.
