### ISSUE TITLE
What's the meaning of "squeeze_idx" in eval_datasets.py?

### ISSUE THREAD

**Issue by MUVGuan** [yoxu515/aot-benchmark#11]
Hello! 
When I read the code in eval_datasets.py, I have a question about the function "read_label" of class VOSTest. 
Could you please tell me the meaning of "squeeze_idx"? When I debug the code, I find that in "__getitem__", it have used "obj_idx" as "squeeze_idx" in "read_label", but it seems no difference between the input label and "squeezed_label", so what's the effect of "squeeze_idx"? And under what circumstances will it be used?
Thank you!

**Comment by z-x-yang** [comment]
A good question. 

In some video sequences of YouTube-VOS, the object number may are smaller than the maximum object index. For example, there are only 3 objects in a sequence, but their indices are 1, 3, 10 instead of 1, 2, 3. Under such kind of cases, we have to squeeze the indices to be compact.

**Comment by MUVGuan** [comment]
> A good question.
> 
> In some video sequences of YouTube-VOS, the object number may are smaller than the maximum object index. For example, there are only 3 objects in a sequence, but their indices are 1, 3, 10 instead of 1, 2, 3. Under such kind of cases, we have to squeeze the indices to be compact.
Thanks for your reply.
After your explanation, I guess the advantage of making indices to be compact is that when extracting the labels of all targets, it can have a smaller tensor. For example, input label is [11, 480, 910], objects' indices are 1, 3, 6, the extracting result is [7, 480, 910], but after compacting it is [4, 480, 910]. So it reduces time and memory, is that right?

**Comment by z-x-yang** [comment]
Yes, it will reduce time and memory when objects' maximum index is larger than the size of the identity bank. But if objects' maximum index is smaller than the size of the identity bank, the time and memory are always the same.

**Comment by MUVGuan** [comment]
Got it, thank you very much!
