### ISSUE TITLE
Could you please release the Swin-AOT checkpoint that only trained on DAVIS&YTB or YTB?

### ISSUE THREAD

**Issue by bo-miao** [yoxu515/aot-benchmark#12]
Hi,

I want to use the Swin-AOT model that is only trained on DAVIS&YTB or YTB, i.e. w/o pre-training on static image datasets. However, I found that one 3090 only supports less than 4 samples in a batch, which affects the convergence of the model, while I only have one GPU right now. May I know is it convenient for you to release this checkpoint (Swin-AOT that is only trained on DAVIS&YTB or YTB, i.e. w/o pre-training on static image datasets) for reference of the later work? 

Thanks.

**Comment by z-x-yang** [comment]
Sorry, we don't have such a checkpoint, but we'll remind you if we have it in the future.

**Comment by bo-miao** [comment]
Received with many thanks!
