### ISSUE TITLE
A question about α in the loss formula of AOST

### ISSUE THREAD

**Issue by MUVGuan** [yoxu515/aot-benchmark#14]
Hello!
In your new model AOST, you use "α" in the loss formula. Is every α_l equal to each other? As the paper says:" To balance the gradient contribution of sub-networks, we have to increase the weight of deeper subnetworks.", I think it means when L=3, α_1 < α_2 < α_3. But the default setting is α=2, and I am very confused about which α_l is set to 2?
Thank you!

**Comment by z-x-yang** [comment]
In α^l, α is a base and l is an exponent. When setting α=2, we have α^1 = 2, α^2=4, α^3=8......

**Comment by MUVGuan** [comment]
Thanks for your reply, I mistakenly thought l represented the subscript.
