### ISSUE TITLE
About the LSTT module

### ISSUE THREAD

**Issue by lsy-dot** [yoxu515/aot-benchmark#16]
When I read the source code of networks/engines/aot_engine.py, I found that only the value was updated when the memory was updated in the update_short_term_memory method. Is there any consideration for not updating the key here?

**Comment by z-x-yang** [comment]
To make the query and the key be matched in the same embedding space, we didn't update the key.

**Comment by lsy-dot** [comment]
I'm very sorry to bother you again. My understanding is that if a new frame of picture introduces new information, the corresponding key and value of memory should also be changed accordingly. I can't understand what you mean the same embedding space？

**Comment by z-x-yang** [comment]
A key in the long-term memory is once a query in the frame where it appears. There is no difference in the network parameters or architectures to produce a key or a query.

**Comment by lsy-dot** [comment]
Thanks for your answer，
