### ISSUE TITLE
The mask of first frame

### ISSUE THREAD

**Issue by Carter-1998** [yoxu515/aot-benchmark#17]
I would like to ask if the target to be split does not appear in the mask of the first frame, can it still be split smoothly in subsequent splits?

**Comment by z-x-yang** [comment]
Sorry, I can't understand what you point to.

**Comment by Carter-1998** [comment]
I apologise for not being clear. I meant if the target of interest does not appear in the first frame, can it still be segmented in subsequent frames？

**Comment by z-x-yang** [comment]
Yes, the framework can do this well. The cases you talked about can be found in many videos on YouTube-VOS.

**Comment by Carter-1998** [comment]
Thanks a lot.



---Original---
From: "Zongxin ***@***.***&gt;
Date: Thu, Apr 14, 2022 22:41 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yoxu515/aot-benchmark] The mask of first frame (Issue #17)




 
Yes, the framework can do this well. The cases you talked about can be found in many videos on YouTube-VOS.

**Comment by 9p15p** [comment]
Hi, @Carter-1998 @z-x-yang 

It seems that Semi-supervised VOS needs the reference mask in the first frame. If we do not provide it, How can the model know which object to segment?
