### ISSUE TITLE
cuda memory issue for multi-scale inference

### ISSUE THREAD

**Issue by haochenheheda** [yoxu515/aot-benchmark#18]
Hi, thanks for your excellent work.
I tried to run multi-scale ([1.0, 1.3]) inference in tools/eval.py on a single A100 (40G). Then I faced the out of memory problem.
So I want to ask about the scales you use in the multi-scale inference. Or is there any way to decrease the memory during inference?
Thanks!

**Comment by z-x-yang** [comment]
I guess your base resolution was set to 480p*1.3 instead of 480p, and thus you ran the inference with a resolution of 480p*1.3*[1.0, 1.3].
