### ISSUE TITLE
Train speed very slow

### ISSUE THREAD

**Issue by MingkunLishigure** [yoxu515/aot-benchmark#19]
I use the original code in Github and train on four A100 GPUS with the Stage = 'ytb',  but it seems that it cost too much time to train this network(For example, 200steps with one hours). If there are total 100000 steps, the training can not just use 0.6 days as you say in the 'Reading Me'.  Will this be caused by using the original code directly? Should I  change some  settings in this code?

**Comment by z-x-yang** [comment]
Can't reproduce the mentioned issue. The training speed should be 0.5s per iteration.
