### ISSUE TITLE
prev_labels of trainer.process_log() maybe wrong?

### ISSUE THREAD

**Issue by z-jiaming** [yoxu515/aot-benchmark#20]
Hi, thanks for your excellent work.

But I confused about why the prev_labels of trainer.process_log() are from all_pred[-2]?
They should be GT?

https://github.com/yoxu515/aot-benchmark/blob/5a7665fc8e0f0e64bc8ba6028b15d9ab32f4c56a/networks/managers/trainer.py#L474

Thanks!

**Comment by z-x-yang** [comment]
You are right. This is a mistake but is useful if you want to visualize the predictions in the previous frame.
