### ISSUE TITLE
Does AOTL use multiple frames in long term memory during the training phase?

### ISSUE THREAD

**Issue by MUVGuan** [yoxu515/aot-benchmark#24]
Hello! Does AOTL use multiple frames in long term memory during the training phase? Or AOTL just uses the first frame in  long term memory to train and uses multiple frames for evaluation?

**Comment by z-x-yang** [comment]
Yes, AOT-L uses multiple frames during training. In detail, AOT-L updates the long-term memory per 2/5 frame for training/evaluation.

**Comment by MUVGuan** [comment]
Thank you very much!
