### ISSUE TITLE
Can I pass in more annotated masks for model to use?

### ISSUE THREAD

**Issue by LilyDaytoy** [yoxu515/aot-benchmark#26]
Thanks for this wonderful work!
I put some well-annotated masks of some key frames of the video in masks directory, but I found that the model is still only using the first frame's mask to propogate.
Can the model make use of more masks (like sparse annotated masks for key frames) to propogate the entire video?
Thanks a lot~

**Comment by z-x-yang** [comment]
The Demo uses only the first frame as a reference frame. But the AOT engine supports using multiple frames as reference frames. To add more reference frames, you can call add_reference_frame directly.

In fact, in the evaluation of YouTube-VOS, some video sequences have more than one reference frame, and we use the above manner to add more reference frames during inference. Please refer to [here](https://github.com/yoxu515/aot-benchmark/blob/5a7665fc8e0f0e64bc8ba6028b15d9ab32f4c56a/networks/managers/evaluator.py#L351) for details.
