### ISSUE TITLE
AOT/DeAOT perfs on MOSE dataset

### ISSUE THREAD

**Issue by bhack** [yoxu515/aot-benchmark#33]
Just in the case you are interested:
https://henghuiding.github.io/MOSE/

**Comment by z-x-yang** [comment]
I have noticed this work, a new challenging benchmark for VOS.

**Comment by bhack** [comment]
Yes but it is already a good baseline. 
A new challenge is also https://taodataset.org/workshop/cvpr23/#competition

**Comment by z-x-yang** [comment]
Yes, I'm watching on this challenge as well. Are you a organizer of this workshop?

**Comment by bhack** [comment]
> Are you a organizer of this workshop?

No, but it seems interesting. The dataset is mainly: https://github.com/Ali2500/BURST-benchmark

**Comment by bhack** [comment]
If you are interested the MOSE competition is available now on CodaLab:
https://codalab.lisn.upsaclay.fr/competitions/10703
