### ISSUE TITLE
Evaluate with more sparse supervision 

### ISSUE THREAD

**Issue by bhack** [yoxu515/aot-benchmark#35]
I was trying to eval some of these models with more sparse supervision e.g. 1 every N frames. 

So I've simply tried to add more reference frames at:

https://github.com/yoxu515/aot-benchmark/blob/1c3a5ec51d81f3e17ff9092aa1e830206d766132/networks/managers/evaluator.py#L316:L324

it seems to work but it is has an impact on the memory with earlier OOM events.  

Have you tried to experiment this setup? Do I need to manipulate something else other then adding reference frames? 
What it could be the relationship with the long term memory gap setting?

**Comment by z-x-yang** [comment]
Utilizing additional reference frames results in increased memory usage. To save memory, perhaps you could prevent the update of long-term memory by setting the gap to a huge number, such as 9999.

**Comment by bhack** [comment]
Yes I've already increased the long-term memory with an higher value.  
What I meant, other then the memory occupancy, how I could think at the long-term memory when I am introducing more sparse reference frames?

**Comment by z-x-yang** [comment]
Reference frames are part of the long-term memory.

**Comment by bhack** [comment]
Yes so probably it is better to not perfectly overlap the long term memory gap with the additional sparse supervision rate.
