### ISSUE TITLE
How to run only main training without pre-training

### ISSUE THREAD

**Issue by fiskrt** [yoxu515/aot-benchmark#43]
I would like to train a model purely on ytVOS and DAVIS. I.e I would like a stage `ytb_dav`.
Is this possible?

**Comment by yoxu515** [comment]
Yes, you might do this by adding a new config.
Similar to configs/ytb.py, a ytb_dav.py may meet your demond. 
self.STAGE_NAME = 'YTB_DAV'
self.DATASETS = ['youtubevos', 'davis2017']
