### ISSUE TITLE
Cannot train model youtubeVOS. Bug in attention.py?

### ISSUE THREAD

**Issue by fiskrt** [yoxu515/aot-benchmark#45]
Hi, I'm trying to train the model (I have not done any pre-training) on only youtubeVOS with
`python tools/train.py --amp --exp_name default --stage ytb  --gpu_num 2 --model aott`.

It loads the dataset 

![image](https://github.com/yoxu515/aot-benchmark/assets/43207511/a64d9b40-f5dc-4669-8a65-dfa8e54edd5d)

and it loads the pretrained backbone model from `./pretrain_models/mobilenet_v2-b0353104.pth` succesfully.
But then when it starts the training it crashes with the following output:

![image](https://github.com/yoxu515/aot-benchmark/assets/43207511/6e713c2f-249a-4bf3-95a9-df1542ae83ac)

**Comment by yoxu515** [comment]
Hi, I will check the code. By the way, it is recommended to install the pytorch correlation library, and you may not encounter this problem with pytorch correlation installed. See [here](https://github.com/yoxu515/aot-benchmark#requirements).

**Comment by fiskrt** [comment]
Thanks for the quick response. And you are correct, after installing correlation from source using
`TORCH_CUDA_ARCH_LIST='8.0' FORCE_CUDA=1 python setup.py install` it now trains.

Another question: what is the reason to install correlation from source instead pip?

**Comment by yoxu515** [comment]
To avoid some unexpected [issues](https://github.com/ClementPinard/Pytorch-Correlation-extension/issues/1). Actually most of the time pip install works fine.
