### ISSUE TITLE
请问如何在不训练阶段1的情况下，直接训练阶段二，是否可以用你们提供的静态模型（AOTT_PRE.pth）作为预训练模型？

### ISSUE THREAD

**Issue by zhanghongyong123456** [yoxu515/aot-benchmark#49]
![image](https://github.com/yoxu515/aot-benchmark/assets/48466610/0cdda895-3550-4356-be22-ff710fe2f8ff)
请问能不训练第一阶段，使用项目提供的模型做预训练模型。直接训练第二阶段

**Comment by yoxu515** [comment]
You need to send the path to AOTT_PRE.pth as the argument '--pretrained_path' when you lauch the training, or directly modify the self.PRETRAIN_MODEL in the configs/pre_ytb_dav.py file. These two ways are equivalent.

**Comment by zhanghongyong123456** [comment]
> You need to send the path to AOTT_PRE.pth as the argument '--pretrained_path' when you lauch the training, or directly modify the self.PRETRAIN_MODEL in the configs/pre_ytb_dav.py file. These two ways are equivalent.

Thank you very much
