### ISSUE TITLE
Question about short update memory function while using DeAOTT

### ISSUE THREAD

**Issue by AntonioConsiglio** [yoxu515/aot-benchmark#57]
Hello, I have two questions:
1) Why in the code https://github.com/yoxu515/aot-benchmark/blob/315c62f0fc0eaaa6c26ede48f32f2ff41e54209a/networks/models/aot.py#L94
we output the "lstt_short_memories" but it is never used?

2) Why here: https://github.com/yoxu515/aot-benchmark/blob/315c62f0fc0eaaa6c26ede48f32f2ff41e54209a/networks/layers/transformer.py#L675 
The 3rd element is always None and in which case we can have curr_ID_V different from None value ? It means that we will have tgt_ID different from None: https://github.com/yoxu515/aot-benchmark/blob/315c62f0fc0eaaa6c26ede48f32f2ff41e54209a/networks/layers/transformer.py#L622

Thank you in advance :) Great work !

**Comment by z-x-yang** [comment]
1. "lstt_short_memories" is consistently used to provide short-term memory (for further information, refer to the AOT publication). If "lstt_short_memories" is always none, then it seems that you did not update the memory after each frame process. You can refer to the code snippet below for an example of how to update memory:
https://github.com/yoxu515/aot-benchmark/blob/315c62f0fc0eaaa6c26ede48f32f2ff41e54209a/tools/demo.py#L217-L218

2. The third element indicates curr_ID_K, which represents the current key embedding for the ID branch. However, based on the DeAOT publication, the ID and visual branches share the same attention map, namely an attention map like "softmax(visual_query * visual_key)." Consequently, curr_ID_K is never used and is thus set to None. Nevertheless, I have kept the relevant code for curr_ID_K in case someone wants to implement their curr_ID_K and use it.

**Comment by AntonioConsiglio** [comment]
> 1. lstt_short_memories

Thank you for your time. 
In the "update_memory" function only the current_memory is used to update the short term memory.
So, where is it used the 4th element of that list, which is "lstt_short_memories"" ?

https://github.com/yoxu515/aot-benchmark/blob/315c62f0fc0eaaa6c26ede48f32f2ff41e54209a/networks/engines/aot_engine.py#L625

https://github.com/yoxu515/aot-benchmark/blob/315c62f0fc0eaaa6c26ede48f32f2ff41e54209a/networks/engines/deaot_engine.py#L20

![image](https://github.com/yoxu515/aot-benchmark/assets/77753494/bafde258-92bb-4027-8670-ecdbb42f2f01)

Here the second element of the list is "lstt_curr_memories":

https://github.com/yoxu515/aot-benchmark/blob/315c62f0fc0eaaa6c26ede48f32f2ff41e54209a/networks/engines/aot_engine.py#L349

https://github.com/yoxu515/aot-benchmark/blob/315c62f0fc0eaaa6c26ede48f32f2ff41e54209a/networks/models/aot.py#L108


That output is used instead when we add the reference frame:

https://github.com/yoxu515/aot-benchmark/blob/315c62f0fc0eaaa6c26ede48f32f2ff41e54209a/networks/engines/aot_engine.py#L188

**Comment by z-x-yang** [comment]
In DeAOT, `lstt_short_memories` is a list including four elements, [visual key, visual value, ID key (always None), ID value]. See:
https://github.com/yoxu515/aot-benchmark/blob/315c62f0fc0eaaa6c26ede48f32f2ff41e54209a/networks/engines/deaot_engine.py#L50C7-L50C7

**Comment by AntonioConsiglio** [comment]
> In DeAOT, `lstt_short_memories` is a list including four elements, [visual key, visual value, ID key (always None), ID value]. See: https://github.com/yoxu515/aot-benchmark/blob/315c62f0fc0eaaa6c26ede48f32f2ff41e54209a/networks/engines/deaot_engine.py#L50C7-L50C7

Ok. Now I got why we use "current" value isntead "local" when we are propagating the mask. Because "local" are the old valuse stored in short_term_memory list. Instead when we have the curr_id_emb you set these variables as the "current" values (they are only reshaped)

**Comment by z-x-yang** [comment]
You are right.
