### ISSUE TITLE
MS-Deaot

### ISSUE THREAD

**Issue by bhack** [yoxu515/aot-benchmark#60]
Was there any specific rationale why you have not experimented with 2x in the multiscale GPM?
https://arxiv.org/abs/2307.02010

**Comment by yoxu515** [comment]
2x features from the backbone is too shallow, and in the actual implementation we even avoid 4x features in attentions due to the high computational burdon of large scale features.
The code of multi-scale AOT can be found in the paot branch of this repo, you can check out it if you are interested.

**Comment by bhack** [comment]
Thanks, it Is that it was already quite hard to recover very fine details with DeAOT.
