### ISSUE TITLE
Recreating the general examples

### ISSUE THREAD

**Issue by johnathanchiu** [yoxu515/aot-benchmark#67]
Do you have some example code to recreate the general examples (the ones of Messi & Kobe)?

**Comment by AntonioConsiglio** [comment]
> Do you have some example code to recreate the general examples (the ones of Messi & Kobe)?

/tools/demo.py

**Comment by z-x-yang** [comment]
Sorry, I tried to search for these two videos (Messi & Kobe) on my laptop but didn't find them.

If you want to compare your methods with AOT/DeAOT, you can use the demo videos in /datasets/Demo. These videos are more complicated and challenging.
