### ISSUE TITLE
Local attention formula

### ISSUE THREAD

**Issue by npmhung** [yoxu515/aot-benchmark#7]
I notice that you use a conv2d (applied on q) for the relative_emb_k. Should it be a fixed embedding as relative_emb_v?

**Comment by z-x-yang** [comment]
The weight of the mentioned conv2d layer is just a learnable relative key embedding as relative_emb_v. 

For the sake of efficiency, I use a conv2d layer to realize the multiplication between the query feature and the relative key embedding.

**Comment by npmhung** [comment]
Thank you!
However, shouldn't we turn off the bias in that conv2d layer? I didn't see any bias in the "Self-Attention with Relative Position Representations" paper.

**Comment by z-x-yang** [comment]
You are right. The bias item is not necessary. I kept the bias since I didn't find any negative impact from it.
