### ISSUE TITLE
No checkpoint in ./results/result/default_AOTT/PRE/ckpt

### ISSUE THREAD

**Issue by MUVGuan** [yoxu515/aot-benchmark#8]
Hello, thanks a lot for your work! 
I'm trying to evaluate DAVIS17, after I use comand `python eval.py --exp_name default --stage pre --model aott --dataset davis2017 --split val --gpu_num 1`, it returns `No checkpoint in ./results/result/default_AOTT/PRE/ckpt.`. I've prepared as [README](https://github.com/yoxu515/aot-benchmark/blob/main/README.md) said, could you please tell me the reason? Thank you very much!

**Comment by z-x-yang** [comment]
Not sure where you put your checkpoint. You could set the checkpoint path by `--ckpt_path path_to_your_checkpoint`.

**Comment by MUVGuan** [comment]
Thanks for your reply! I've found the reason, it was a mistake. I didn't train before evaluate, so there was no checkpoint, now I use yours pre-trained models directly and it's ok.
